services:
#  swapi:
#    image: juriy/swapi:1.0.0
#    ports:
#      - "8000:8000"
#    environment:
#      PAGE_SIZE: 100
#    command:
#      - sh
#      - "-c"
#      - |
#        # Update the pagination to have all resources directly without pagination
#        sed -i "s/'PAGINATE_BY': 10/'PAGINATE_BY': 500/" swapi/settings.py
#        ./run.sh
  nginx:
    image: nginx:1.25.5-alpine
    ports:
      - "8000:80"
    configs:
      - source: hugo_awards
        target: /usr/share/nginx/html/hugo.json


configs:
  hugo_awards:
    content: |
      {
        "count": 6,
        "results": [
          {
            "title": "Nettle & Bone",
            "author": "T. Kingfisher",
            "year":  2023
          },
          {
            "title": "A Desolation Called Peace",
            "author": "Arkady Martine",
            "year":  2022
          },
          {
            "title": "Network Effect",
            "author": "Martha Wells",
            "year":  2021
          },
          {
            "title": "A Memory Called Empire",
            "author": "Arkady Martine",
            "year":  2020
          },
          {
            "title": "The Calculating Stars",
            "author": "Mary Robinette Kowal",
            "year":  2019
          },
          {
            "title": "The Stone Sky",
            "author": "N. K. Jemisin",
            "year":  2018
          }
        ]
      }
            
